data: ./datasets/visible/data.yaml
epochs: 100
imgsz: 640
batch: 8
device: 0
workers: 8
rect: true
pretrained: true
optimizer: AdamW
lr0: 0.001
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 3
box: 10.0
cls: 1.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
translate: 0.1
scale: 0.5
fliplr: 0.5
mosaic: 1.0
project: models/yolo
name: multiclass_exp
exist_ok: true